/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type GameStateStruct = {
  accepted: boolean;
  pot: BigNumberish;
  startingPlayer: AddressLike;
  activePlayer: AddressLike;
  timeout: BigNumberish;
  action1: BigNumberish;
  action2: BigNumberish;
  action3: BigNumberish;
};

export type GameStateStructOutput = [
  accepted: boolean,
  pot: bigint,
  startingPlayer: string,
  activePlayer: string,
  timeout: bigint,
  action1: bigint,
  action2: bigint,
  action3: bigint
] & {
  accepted: boolean;
  pot: bigint;
  startingPlayer: string;
  activePlayer: string;
  timeout: bigint;
  action1: bigint;
  action2: bigint;
  action3: bigint;
};

export type GameOutcomeStruct = {
  gid: BigNumberish;
  cardA: BigNumberish;
  cardB: BigNumberish;
  winner: AddressLike;
  outcome: BigNumberish;
  rematchGid: BigNumberish;
};

export type GameOutcomeStructOutput = [
  gid: bigint,
  cardA: bigint,
  cardB: bigint,
  winner: string,
  outcome: bigint,
  rematchGid: bigint
] & {
  gid: bigint;
  cardA: bigint;
  cardB: bigint;
  winner: string;
  outcome: bigint;
  rematchGid: bigint;
};

export type GameStruct = {
  gid: BigNumberish;
  rematchingGid: BigNumberish;
  playerA: AddressLike;
  playerB: AddressLike;
  state: GameStateStruct;
  outcome: GameOutcomeStruct;
};

export type GameStructOutput = [
  gid: bigint,
  rematchingGid: bigint,
  playerA: string,
  playerB: string,
  state: GameStateStructOutput,
  outcome: GameOutcomeStructOutput
] & {
  gid: bigint;
  rematchingGid: bigint;
  playerA: string;
  playerB: string;
  state: GameStateStructOutput;
  outcome: GameOutcomeStructOutput;
};

export type PermissionStruct = { publicKey: BytesLike; signature: BytesLike };

export type PermissionStructOutput = [publicKey: string, signature: string] & {
  publicKey: string;
  signature: string;
};

export type SealedUintStruct = { data: string; utype: BigNumberish };

export type SealedUintStructOutput = [data: string, utype: bigint] & {
  data: string;
  utype: bigint;
};

export declare namespace FHEKuhnPoker {
  export type UserGameStateStruct = {
    game: GameStruct;
    selfChips: BigNumberish;
    opponentChips: BigNumberish;
    activeGid: BigNumberish;
    rematchGid: BigNumberish;
    selfGid: BigNumberish;
    opponentGid: BigNumberish;
  };

  export type UserGameStateStructOutput = [
    game: GameStructOutput,
    selfChips: bigint,
    opponentChips: bigint,
    activeGid: bigint,
    rematchGid: bigint,
    selfGid: bigint,
    opponentGid: bigint
  ] & {
    game: GameStructOutput;
    selfChips: bigint;
    opponentChips: bigint;
    activeGid: bigint;
    rematchGid: bigint;
    selfGid: bigint;
    opponentGid: bigint;
  };
}

export interface FHEKuhnPokerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelSearch"
      | "chips"
      | "dealMeIn"
      | "eGameCardA"
      | "eGameCardB"
      | "eip712Domain"
      | "findGame"
      | "games"
      | "getGame"
      | "getGameCard"
      | "getPairGames"
      | "getUserGameState"
      | "getUserGames"
      | "gid"
      | "openGameId"
      | "performAction"
      | "rematch"
      | "resign"
      | "timeoutDuration"
      | "timeoutOpponent"
      | "userActiveGame"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChipTaken"
      | "EIP712DomainChanged"
      | "GameCancelled"
      | "GameCreated"
      | "GameJoined"
      | "PerformedGameAction"
      | "PlayerDealtIn"
      | "RematchAccepted"
      | "RematchCreated"
      | "WonByFold"
      | "WonByResignation"
      | "WonByShowdown"
      | "WonByTimeout"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelSearch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "chips", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "dealMeIn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eGameCardA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eGameCardB",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "findGame", values?: undefined): string;
  encodeFunctionData(functionFragment: "games", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameCard",
    values: [PermissionStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairGames",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserGameState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserGames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "gid", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "openGameId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "performAction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "rematch", values?: undefined): string;
  encodeFunctionData(functionFragment: "resign", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timeoutDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutOpponent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userActiveGame",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelSearch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chips", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dealMeIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eGameCardA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eGameCardB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "findGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameCard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPairGames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserGameState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserGames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "openGameId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rematch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resign", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timeoutDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutOpponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userActiveGame",
    data: BytesLike
  ): Result;
}

export namespace ChipTakenEvent {
  export type InputTuple = [player: AddressLike, gid: BigNumberish];
  export type OutputTuple = [player: string, gid: bigint];
  export interface OutputObject {
    player: string;
    gid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCancelledEvent {
  export type InputTuple = [player: AddressLike, gid: BigNumberish];
  export type OutputTuple = [player: string, gid: bigint];
  export interface OutputObject {
    player: string;
    gid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCreatedEvent {
  export type InputTuple = [playerA: AddressLike, gid: BigNumberish];
  export type OutputTuple = [playerA: string, gid: bigint];
  export interface OutputObject {
    playerA: string;
    gid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameJoinedEvent {
  export type InputTuple = [playerB: AddressLike, gid: BigNumberish];
  export type OutputTuple = [playerB: string, gid: bigint];
  export interface OutputObject {
    playerB: string;
    gid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PerformedGameActionEvent {
  export type InputTuple = [
    player: AddressLike,
    gid: BigNumberish,
    action: BigNumberish
  ];
  export type OutputTuple = [player: string, gid: bigint, action: bigint];
  export interface OutputObject {
    player: string;
    gid: bigint;
    action: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerDealtInEvent {
  export type InputTuple = [user: AddressLike, chips: BigNumberish];
  export type OutputTuple = [user: string, chips: bigint];
  export interface OutputObject {
    user: string;
    chips: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RematchAcceptedEvent {
  export type InputTuple = [playerB: AddressLike, gid: BigNumberish];
  export type OutputTuple = [playerB: string, gid: bigint];
  export interface OutputObject {
    playerB: string;
    gid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RematchCreatedEvent {
  export type InputTuple = [playerA: AddressLike, gid: BigNumberish];
  export type OutputTuple = [playerA: string, gid: bigint];
  export interface OutputObject {
    playerA: string;
    gid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WonByFoldEvent {
  export type InputTuple = [
    winner: AddressLike,
    gid: BigNumberish,
    pot: BigNumberish
  ];
  export type OutputTuple = [winner: string, gid: bigint, pot: bigint];
  export interface OutputObject {
    winner: string;
    gid: bigint;
    pot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WonByResignationEvent {
  export type InputTuple = [
    winner: AddressLike,
    gid: BigNumberish,
    pot: BigNumberish
  ];
  export type OutputTuple = [winner: string, gid: bigint, pot: bigint];
  export interface OutputObject {
    winner: string;
    gid: bigint;
    pot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WonByShowdownEvent {
  export type InputTuple = [
    winner: AddressLike,
    gid: BigNumberish,
    pot: BigNumberish
  ];
  export type OutputTuple = [winner: string, gid: bigint, pot: bigint];
  export interface OutputObject {
    winner: string;
    gid: bigint;
    pot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WonByTimeoutEvent {
  export type InputTuple = [
    winner: AddressLike,
    gid: BigNumberish,
    pot: BigNumberish
  ];
  export type OutputTuple = [winner: string, gid: bigint, pot: bigint];
  export interface OutputObject {
    winner: string;
    gid: bigint;
    pot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEKuhnPoker extends BaseContract {
  connect(runner?: ContractRunner | null): FHEKuhnPoker;
  waitForDeployment(): Promise<this>;

  interface: FHEKuhnPokerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelSearch: TypedContractMethod<[], [void], "nonpayable">;

  chips: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  dealMeIn: TypedContractMethod<
    [chipCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  eGameCardA: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  eGameCardB: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  findGame: TypedContractMethod<[], [void], "nonpayable">;

  games: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        GameStateStructOutput,
        GameOutcomeStructOutput
      ] & {
        gid: bigint;
        rematchingGid: bigint;
        playerA: string;
        playerB: string;
        state: GameStateStructOutput;
        outcome: GameOutcomeStructOutput;
      }
    ],
    "view"
  >;

  getGame: TypedContractMethod<
    [_gid: BigNumberish],
    [GameStructOutput],
    "view"
  >;

  getGameCard: TypedContractMethod<
    [permission: PermissionStruct, _gid: BigNumberish],
    [SealedUintStructOutput],
    "view"
  >;

  getPairGames: TypedContractMethod<
    [_playerA: AddressLike, _playerB: AddressLike],
    [GameStructOutput[]],
    "view"
  >;

  getUserGameState: TypedContractMethod<
    [_user: AddressLike],
    [FHEKuhnPoker.UserGameStateStructOutput],
    "view"
  >;

  getUserGames: TypedContractMethod<
    [user: AddressLike],
    [GameStructOutput[]],
    "view"
  >;

  gid: TypedContractMethod<[], [bigint], "view">;

  openGameId: TypedContractMethod<[], [bigint], "view">;

  performAction: TypedContractMethod<
    [action: BigNumberish],
    [void],
    "nonpayable"
  >;

  rematch: TypedContractMethod<[], [void], "nonpayable">;

  resign: TypedContractMethod<[], [void], "nonpayable">;

  timeoutDuration: TypedContractMethod<[], [bigint], "view">;

  timeoutOpponent: TypedContractMethod<[], [void], "nonpayable">;

  userActiveGame: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelSearch"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "chips"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "dealMeIn"
  ): TypedContractMethod<[chipCount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "eGameCardA"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "eGameCardB"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "findGame"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        GameStateStructOutput,
        GameOutcomeStructOutput
      ] & {
        gid: bigint;
        rematchingGid: bigint;
        playerA: string;
        playerB: string;
        state: GameStateStructOutput;
        outcome: GameOutcomeStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<[_gid: BigNumberish], [GameStructOutput], "view">;
  getFunction(
    nameOrSignature: "getGameCard"
  ): TypedContractMethod<
    [permission: PermissionStruct, _gid: BigNumberish],
    [SealedUintStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairGames"
  ): TypedContractMethod<
    [_playerA: AddressLike, _playerB: AddressLike],
    [GameStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserGameState"
  ): TypedContractMethod<
    [_user: AddressLike],
    [FHEKuhnPoker.UserGameStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserGames"
  ): TypedContractMethod<[user: AddressLike], [GameStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "gid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openGameId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "performAction"
  ): TypedContractMethod<[action: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rematch"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resign"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeoutDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "timeoutOpponent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userActiveGame"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "ChipTaken"
  ): TypedContractEvent<
    ChipTakenEvent.InputTuple,
    ChipTakenEvent.OutputTuple,
    ChipTakenEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "GameCancelled"
  ): TypedContractEvent<
    GameCancelledEvent.InputTuple,
    GameCancelledEvent.OutputTuple,
    GameCancelledEvent.OutputObject
  >;
  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameJoined"
  ): TypedContractEvent<
    GameJoinedEvent.InputTuple,
    GameJoinedEvent.OutputTuple,
    GameJoinedEvent.OutputObject
  >;
  getEvent(
    key: "PerformedGameAction"
  ): TypedContractEvent<
    PerformedGameActionEvent.InputTuple,
    PerformedGameActionEvent.OutputTuple,
    PerformedGameActionEvent.OutputObject
  >;
  getEvent(
    key: "PlayerDealtIn"
  ): TypedContractEvent<
    PlayerDealtInEvent.InputTuple,
    PlayerDealtInEvent.OutputTuple,
    PlayerDealtInEvent.OutputObject
  >;
  getEvent(
    key: "RematchAccepted"
  ): TypedContractEvent<
    RematchAcceptedEvent.InputTuple,
    RematchAcceptedEvent.OutputTuple,
    RematchAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "RematchCreated"
  ): TypedContractEvent<
    RematchCreatedEvent.InputTuple,
    RematchCreatedEvent.OutputTuple,
    RematchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "WonByFold"
  ): TypedContractEvent<
    WonByFoldEvent.InputTuple,
    WonByFoldEvent.OutputTuple,
    WonByFoldEvent.OutputObject
  >;
  getEvent(
    key: "WonByResignation"
  ): TypedContractEvent<
    WonByResignationEvent.InputTuple,
    WonByResignationEvent.OutputTuple,
    WonByResignationEvent.OutputObject
  >;
  getEvent(
    key: "WonByShowdown"
  ): TypedContractEvent<
    WonByShowdownEvent.InputTuple,
    WonByShowdownEvent.OutputTuple,
    WonByShowdownEvent.OutputObject
  >;
  getEvent(
    key: "WonByTimeout"
  ): TypedContractEvent<
    WonByTimeoutEvent.InputTuple,
    WonByTimeoutEvent.OutputTuple,
    WonByTimeoutEvent.OutputObject
  >;

  filters: {
    "ChipTaken(address,uint256)": TypedContractEvent<
      ChipTakenEvent.InputTuple,
      ChipTakenEvent.OutputTuple,
      ChipTakenEvent.OutputObject
    >;
    ChipTaken: TypedContractEvent<
      ChipTakenEvent.InputTuple,
      ChipTakenEvent.OutputTuple,
      ChipTakenEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "GameCancelled(address,uint256)": TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;
    GameCancelled: TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;

    "GameCreated(address,uint256)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameJoined(address,uint256)": TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;
    GameJoined: TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;

    "PerformedGameAction(address,uint256,uint8)": TypedContractEvent<
      PerformedGameActionEvent.InputTuple,
      PerformedGameActionEvent.OutputTuple,
      PerformedGameActionEvent.OutputObject
    >;
    PerformedGameAction: TypedContractEvent<
      PerformedGameActionEvent.InputTuple,
      PerformedGameActionEvent.OutputTuple,
      PerformedGameActionEvent.OutputObject
    >;

    "PlayerDealtIn(address,uint256)": TypedContractEvent<
      PlayerDealtInEvent.InputTuple,
      PlayerDealtInEvent.OutputTuple,
      PlayerDealtInEvent.OutputObject
    >;
    PlayerDealtIn: TypedContractEvent<
      PlayerDealtInEvent.InputTuple,
      PlayerDealtInEvent.OutputTuple,
      PlayerDealtInEvent.OutputObject
    >;

    "RematchAccepted(address,uint256)": TypedContractEvent<
      RematchAcceptedEvent.InputTuple,
      RematchAcceptedEvent.OutputTuple,
      RematchAcceptedEvent.OutputObject
    >;
    RematchAccepted: TypedContractEvent<
      RematchAcceptedEvent.InputTuple,
      RematchAcceptedEvent.OutputTuple,
      RematchAcceptedEvent.OutputObject
    >;

    "RematchCreated(address,uint256)": TypedContractEvent<
      RematchCreatedEvent.InputTuple,
      RematchCreatedEvent.OutputTuple,
      RematchCreatedEvent.OutputObject
    >;
    RematchCreated: TypedContractEvent<
      RematchCreatedEvent.InputTuple,
      RematchCreatedEvent.OutputTuple,
      RematchCreatedEvent.OutputObject
    >;

    "WonByFold(address,uint256,uint256)": TypedContractEvent<
      WonByFoldEvent.InputTuple,
      WonByFoldEvent.OutputTuple,
      WonByFoldEvent.OutputObject
    >;
    WonByFold: TypedContractEvent<
      WonByFoldEvent.InputTuple,
      WonByFoldEvent.OutputTuple,
      WonByFoldEvent.OutputObject
    >;

    "WonByResignation(address,uint256,uint256)": TypedContractEvent<
      WonByResignationEvent.InputTuple,
      WonByResignationEvent.OutputTuple,
      WonByResignationEvent.OutputObject
    >;
    WonByResignation: TypedContractEvent<
      WonByResignationEvent.InputTuple,
      WonByResignationEvent.OutputTuple,
      WonByResignationEvent.OutputObject
    >;

    "WonByShowdown(address,uint256,uint256)": TypedContractEvent<
      WonByShowdownEvent.InputTuple,
      WonByShowdownEvent.OutputTuple,
      WonByShowdownEvent.OutputObject
    >;
    WonByShowdown: TypedContractEvent<
      WonByShowdownEvent.InputTuple,
      WonByShowdownEvent.OutputTuple,
      WonByShowdownEvent.OutputObject
    >;

    "WonByTimeout(address,uint256,uint256)": TypedContractEvent<
      WonByTimeoutEvent.InputTuple,
      WonByTimeoutEvent.OutputTuple,
      WonByTimeoutEvent.OutputObject
    >;
    WonByTimeout: TypedContractEvent<
      WonByTimeoutEvent.InputTuple,
      WonByTimeoutEvent.OutputTuple,
      WonByTimeoutEvent.OutputObject
    >;
  };
}
