/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fheOsSol from "./FheOS.sol";
export type { fheOsSol };
import type * as access from "./access";
export type { access };
import type * as utils from "./utils";
export type { utils };
export type { FHE } from "./FHE";
